DROP DATABASE IF EXISTS ts_tenjin_api;
CREATE DATABASE ts_tenjin_api;
USE ts_tenjin_api;
SHOW TABLES;
SELECT * FROM categories;
SELECT * FROM tags;
SELECT * FROM mentors;
SELECT * FROM educations;
SELECT * FROM skills;
SELECT * FROM assistants;